### ISSUE TITLE
Initialization fault during launch.

### ISSUE THREAD

**Issue by Noemata** [aurora-lzzp/Aurora-Weather#2]
I am running into an initialization problem during launch.

At startup, DismissedEventHandler() gets called early.  It in turn calls SettingsModel.Get(), so far so good.  Inside the Get(), a call to Cities.Get() is made (the start of the problem).

Within:

        public static Cities Get()
        {
            Cities c = new Cities();
            try
            {
                var container = RoamingSettingsHelper.GetContainer("Cities");
                c.CurrentIndex = (int)container.Values["CurrentIndex"];
...

The application faults on the last line above during startup, because the value of "CurrentIndex" isn't set yet.  You catch the fault.  Unfortunately "Cities" is only partially initialized as a result

Later on you call:

        private void UpdatePosition(Geoposition pos)
        {
            var task = ThreadPool.RunAsync(async (work) =>
             {
                 await Context.CalcPosition(pos);
             });
        }

Inside:

        internal async Task CalcPosition(Geoposition pos)
        {

            var final = Models.Location.GetNearsetLocation(cities,
                new Models.Location((float)pos.Coordinate.Point.Position.Latitude, (float)pos.Coordinate.Point.Position.Longitude));

            if (Cities.LocatedCity.Id == final.ToArray()[0].Id)

...

The application faults on when this if is evaluated:
 if (Cities.LocatedCity.Id == final.ToArray()[0].id) 

Because Cities.LocatedCity is null due to the partial initialization of Cities.

It's not obvious to me how this should be fixed.  It looks like you need to do some initialization within:

        public CitiesSettingViewModel()

after these calls:

                var data = await FileIOHelper.ReadStringFromAssetsAsync("cityid.txt");
                var result = JsonHelper.FromJson<CityIdContract>(data);
                cities = CityInfo.CreateList(result);
                OnRefreshComplete();

So that "Cities" is fully initialized.  Just guessing.

**Comment by Noemata** [comment]
I was able to correct the first part of the launch problem by adjust the if above as follows:

            if (Cities.LocatedCity != null && Cities.LocatedCity.Id == final.ToArray()[0].Id)

Now I get an exception on the line:

                                     var keys = (await FileIOHelper.ReadStringFromAssetsAsync("Key")).Split(new string[] { ":|:" }, StringSplitOptions.RemoveEmptyEntries);

I assume this is the key file you were referring to.  Could you please send a private email with the details for how to resolve this to: mario [at] noemata.org

I can appreciate why this is not published.  Thank you.

**Comment by pkzxs** [comment]
I just pushed a commit to fix that problem.
[Commit·0df8fd4](https://github.com/aurora-lzzp/Aurora-Weather/commit/0df8fd4f5414ae0bc57cc1f0437db7dd8150c860)
Thanks a lot.
So why I made that big fault? I think the reason is that I didn't clear the settings data at each redeployment. So the located city always be there, and can't cause exception.
Because of this silly problem, a huge number of crashes happened when people install this app at first time, so I uploaded a new package to Windows Store hastily. Thank you again.
About the key, you can read the updated readme document to find out how to get it, it is totally free.

**Comment by pkzxs** [comment]
I also sent u that file
