### ISSUE TITLE
Api key handling.

### ISSUE THREAD

**Issue by Noemata** [aurora-lzzp/Aurora-Weather#3]
I adjusted the Api key handling as follows:

        private async Task FetchDataAsync()
        {
            await SearchExistingDataAsync();
            string resstr;

            // MP! added API key fault handling.

            if (currentId != null)
            {
                if (!storedDatas.Equals(default(KeyValuePair<string, string>)))
                {
                    resstr = storedDatas.Value;

                    if (resstr.Contains("Apikey does not exist"))
                    {
                        this.OnFetchDataFailed(this, new FetchDataFailedEventArgs("Api key does not exist"));
                        return;
                    }

                    if (resstr.Length > 31)
                    {
                        var resjson = HeWeatherContract.Generate(resstr);
                        fetchresult = new HeWeatherModel(resjson);
                        return;
                    }
                }
                var keys = (await FileIOHelper.ReadStringFromAssetsAsync("Key")).Split(new string[] { ":|:" }, StringSplitOptions.RemoveEmptyEntries);
                var param = new string[] { "cityid=" + currentId };
                resstr = await BaiduRequestHelper.RequestWithKeyAsync("http://apis.baidu.com/heweather/pro/weather", param, keys[0]);
                if (resstr.Contains("Apikey does not exist"))
                {
                    this.OnFetchDataFailed(this, new FetchDataFailedEventArgs("Api key does not exist"));
                    return;
                }
                if (resstr == null)
                {
                    this.OnFetchDataFailed(this, new FetchDataFailedEventArgs("Network_Error"));
                    return;
                }
                var resjson1 = HeWeatherContract.Generate(resstr);
                fetchresult = new HeWeatherModel(resjson1);
                if (fetchresult.Status != HeWeatherStatus.ok)
                {
                    this.OnFetchDataFailed(this, new FetchDataFailedEventArgs("Service_Unavailable"));
                    return;
                }
                var task = ThreadPool.RunAsync(async (work) =>
                {
                    await settings.Cities.SaveDataAsync(currentId, resstr);
                    currentCityModel.Update();
                    if (settings.Cities.CurrentIndex != -1)
                    {
                        settings.Cities.SavedCities[settings.Cities.CurrentIndex] = currentCityModel;
                    }
                    else
                    {
                        settings.Cities.LocatedCity = currentCityModel;
                    }
                    settings.Cities.Save();
                });

            }
            else throw new NullReferenceException();

        }

Unfortunately the fault handling still crashes the application somewhere up stream.  You'll want to add API key fault handling, and have the application gracefully fail.  I also noticed that the invalid key is used on a subsequent run, that would be ok if the original key had been stored properly after the initial key fault, but now the key is even more invalid because it was stored in corrupted form, making it impossible to recover the original key since it is now stored in corrupted form.

It's possible that a key might be temporarily invalid (key owner is late paying for subscription), thus you'll want to revert back to the original key when a key fault is detected, rather than corrupting the original key.

**Comment by pkzxs** [comment]
Ok, I will push that soon
