### ISSUE TITLE
Nice App!

### ISSUE THREAD

**Issue by Noemata** [aurora-lzzp/Aurora-Weather#4]
I decided to cheat, and pulled the "Key" file from your store version of the application to get things to work.  Very nice!

I put in a little extra effort to get this going because I thought this might be well done, and it is.

You will probably want to encrypt the key in some internal resource rather than have it in such an obvious Key file.  It's much harder to reach into Windows Store binary elements.  The asset files are easily accessible once you download a store app.

I would have created my own key file, but I can't read Chinese!  The internationalization still needs some work.  The regional bits were not correct on my "ca" (Canadian") language setup.

Nonetheless, very well done!

**Comment by pkzxs** [comment]
Yeah, I'm a Chinese, and pool in English, so I just want to find somebody to improve the localization.
that key will be updated and encrypted soon, but because of a bug in `Windows.Security.Cryptography`, I can't use the native way to decrypt keys, so I'm still finding the solution.
