### ISSUE TITLE
Localization Strings incorrect.

### ISSUE THREAD

**Issue by Noemata** [aurora-lzzp/Aurora-Weather#5]
Locazation Issue below:

    public class TempratureConverterWithoutDecoration : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            if (value == null)
            {
                return "...";
            }
            var t = (Temperature)value;
            switch (TempratureConverter.Parameter)
            {
                case TemperatureParameter.Celsius: return t.Celsius.ToString("0") + "¡ã";
                case TemperatureParameter.Fahrenheit: return t.Fahrenheit.ToString("0") + "¡ã";
                case TemperatureParameter.Kelvin: return t.Kelvin.ToString("0");
                default: return t.Celsius.ToString("0") + "¡ã";
            }
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }

The value for  "¡ã", should be pulled in from the devices Country setting.

Similarly in:

        private StringBuilder SetDegree(uint degree, StringBuilder sb)
        {
            sb.Append(degree);
            // MP! was:
            //sb.Append('¡ã');
            sb.Append('°');
            return sb;
        }

Initially I assumed the above was a Unicode problem, hence my change.  This type of problem would go away by using the devices country setting for "degrees".

Look at:

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/NumberFormatting
http://stackoverflow.com/questions/26035714/getting-regional-settings-winrt

**Comment by pkzxs** [comment]
oh, I find the reason. Github Extension in Visual Studio is not compatible with Chinese may be, in my computer, that above is correctly coded as "°", but when I push to github, it seems to be changed by github extension then goes wrong. Did you use the store version? I think that should be displayed correctly.

**Comment by Noemata** [comment]
Interesting.  You are right.  The store version has the correct value.  I thought perhaps there might be a regional version of "°".  Perhaps it's the one character that is the same everywhere.

One other thing I noticed, when the time is displayed, the value bounces around a little when the seconds tick by.  You might want to "box" the individual characters in a grid, or use a fixed spacing font for the time.

**Comment by pkzxs** [comment]
I'm preparing to commit the correct version in the morning(you know, it is 1AM in China now).
About the clock's problem, I have already noticed, it will be fixed in next commit too.

**Comment by Noemata** [comment]
Sounds good.

You should go to bed!

I was wondering, would you be interesting in collaborating on this?  I 
have some ideas that will make this into something much more significant 
and lucrative.

A few years back I worked on an air quality monitoring system AQMS for a 
company in the Sudbury, Ontario, Canada area.  They still use my Flash 
app today to show monitoring station information in a very graphical 
way!  There is a very serious pollution problem in the area due to 
sulfur emissions by local mining companies.  Sometimes alarms have to be 
sounded.

What I have in mind is to build a plugin system into your app.  I have a 
couple other ideas that I am willing to share if we can sort something 
out on how the collaboration might work.

Let me know,

Good night,

Mario

**Comment by pkzxs** [comment]
These two commits:
[6f9a575](https://github.com/aurora-lzzp/Aurora-Weather/commit/6f9a575aa9cf9562b1b838dc8940fdf5414be70b)    
[f23c95d](https://github.com/aurora-lzzp/Aurora-Weather/commit/f23c95dd4ca641b534d54fb171738232d059a9cc)    
should solve problems.   

About the collaboration, that's really great, but I'm preparing to get my Bachelor's Degree so I'don't have much time, sorry. May be next year I will be free to write code XD.
